const gameData = {
    // ==========================================
    // ARABIC (Optimized for Coptic Orthodox Context)
    // ==========================================
    ar: [
        {id:1,t:"من هو النبي الذي ابتلعه الحوت؟",o:["موسى","يونان","إشعياء","دانيال"],c:1,l:1,r:"\"وَأَمَّا الرَّبُّ فَأَعَدَّ حُوتًا عَظِيمًا لِيَبْتَلِعَ يُونَانَ.\" (يونان 1: 17)"},
        {id:2,t:"كم عدد أسباط إسرائيل؟",o:["٧","١٠","١٢","٤٠"],c:2,l:1,r:"\"جَمِيعُ هؤُلاَءِ هُمْ أَسْبَاطُ إِسْرَائِيلَ الاثْنَا عَشَرَ.\" (تكوين 49: 28)"},
        {id:3,t:"في أي مدينة ولد السيد المسيح؟",o:["الناصرة","أورشليم","بيت لحم","كفرناحوم"],c:2,l:1,r:"\"وَلَمَّا وُلِدَ يَسُوعُ فِي بَيْتِ لَحْمِ الْيَهُودِيَّةِ...\" (متى 2: 1)"},
        {id:4,t:"ما هو أول سفر في الكتاب المقدس؟",o:["الخروج","التكوين","المزامير","الرؤيا"],c:1,l:1,r:"\"فِي الْبَدْءِ خَلَقَ اللهُ السَّمَاوَاتِ وَالأَرْضَ.\" (تكوين 1: 1)"},
        {id:5,t:"من هو التلميذ الذي أنكر السيد المسيح ثلاث مرات؟",o:["يهوذا الإسخريوطي","يوحنا الحبيب","بطرس الرسول","توما الشكاك"],c:2,l:1,r:"\"فَتَذَكَّرَ بُطْرُسُ كَلاَمَ يَسُوعَ... إِنَّكَ... تُنْكِرُنِي ثَلاَثَ مَرَّاتٍ.\" (متى 26: 75)"},
        {id:6,t:"ماذا خلق الله في اليوم الرابع؟",o:["النور","الجلد","الشمس والقمر والنجوم","الطيور والأسماك"],c:2,l:1,r:"\"فَعَمِلَ اللهُ النُّورَيْنِ الْعَظِيمَيْنِ... وَالنُّجُومَ.\" (تكوين 1: 16)"},
        {id:7,t:"من هو الرجل الذي عاش أطول عمر في الكتاب المقدس؟",o:["نوح","آدم","متوشالح","إبراهيم"],c:2,l:1,r:"\"فَكَانَتْ كُلُّ أَيَّامِ مَتُوشَالَحَ تِسْعَمِئَةٍ وَتِسْعًا وَسِتِّينَ سَنَةً.\" (تكوين 5: 27)"},
        {id:8,t:"ما هي المهنة التي كان يعمل بها داود قبل أن يصبح ملكاً؟",o:["نجار","راعي غنم","صياد سمك","جابي ضرائب"],c:1,l:1,r:"\"بَقِيَ بَعْدُ الصَّغِيرُ وَهُوَذَا هُوَ يَرْعَى الْغَنَمَ.\" (صموئيل الأول 16: 11)"},
        {id:9,t:"كم يوماً صام السيد المسيح في البرية؟",o:["٣ أيام","٧ أيام","٣٠ يوماً","٤٠ يوماً"],c:3,l:1,r:"\"فَبَعْدَ مَا صَامَ أَرْبَعِينَ نَهَارًا وَأَرْبَعِينَ لَيْلَةً، جَاعَ أَخِيرًا.\" (متى 4: 2)"},
        {id:10,t:"من الذي أمره الله ببناء الفلك؟",o:["إبراهيم","موسى","نوح","يعقوب"],c:2,l:1,r:"\"اِصْنَعْ لِنَفْسِكَ فُلْكًا مِنْ خَشَبِ جُفْرٍ.\" (تكوين 6: 14)"},
        {id:11,t:"من هو الصبي الذي هزم العملاق جليات؟",o:["شاول","يوناثان","داود","شمشون"],c:2,l:1,r:"\"فَتَمَكَّنَ دَاوُدُ مِنَ الْفِلِسْطِينِيِّ بِالْمِقْلاَعِ وَالْحَجَرِ.\" (صموئيل الأول 17: 50)"},
        {id:12,t:"ما هو اسم أول إنسان خلقه الله؟",o:["نوح","إبراهيم","آدم","قايين"],c:2,l:1,r:"\"وَجَبَلَ الرَّبُّ الإِلهُ آدَمَ تُرَابًا مِنَ الأَرْضِ.\" (تكوين 2: 7)"},
        {id:13,t:"ما هي أول معجزة صنعها السيد المسيح؟",o:["المشي على الماء","تحويل الماء إلى خمر","شفاء الأبرص","إشباع الجموع"],c:1,l:1,r:"\"هذِهِ بِدَايَةُ الآيَاتِ فَعَلَهَا يَسُوعُ فِي قَانَا الْجَلِيلِ.\" (يوحنا 2: 11)"},
        {id:14,t:"من هو النبي الذي استلم الوصايا العشر؟",o:["إبراهيم","إسحاق","يعقوب","موسى"],c:3,l:1,r:"\"ثُمَّ أَعْطَى مُوسَى... لَوْحَيِ الشَّهَادَةِ.\" (خروج 31: 18)"},
        {id:15,t:"كم عدد الأناجيل القانونية في العهد الجديد؟",o:["٣","٤","٥","٦"],c:1,l:1,r:"(متى، مرقس، لوقا، يوحنا)."},
        {id:16,t:"ما هي العلامة التي أعطاها الله لنوح بعد الطوفان؟",o:["عمود النار","قوس قزح","النجمة","العليقة"],c:1,l:1,r:"\"وَضَعْتُ قَوْسِي فِي السَّحَابِ فَتَكُونُ عَلاَمَةَ مِيثَاق...\" (تكوين 9: 13)"},
        {id:17,t:"من هو الذي باعه إخوته للإسماعيليين؟",o:["بنيامين","يوسف","رأوبين","لاوي"],c:1,l:1,r:"\"فَبَاعُوا يُوسُفَ لِلإِسْمَاعِيلِيِّينَ... فَأَتَوْا بِيُوسُفَ إِلَى مِصْرَ.\" (تكوين 37: 28)"},
        {id:18,t:"ما هي أقصر آية في الكتاب المقدس؟",o:["الله محبة","افرحوا","بكى يسوع","صلوا بلا انقطاع"],c:2,l:1,r:"\"بَكَى يَسُوعُ.\" (يوحنا 11: 35)"},
        {id:19,t:"من هي المرأة التي صلت من أجل ابن فأعطاها الله صموئيل؟",o:["حنة","فننة","راحيل","ليئة"],c:0,l:1,r:"\"وَدَعَتِ اسْمَهُ صَمُوئِيلَ قَائِلَةً: لأَنِّي مِنَ الرَّبِّ سَأَلْتُهُ.\" (صموئيل الأول 1: 20)"},
        {id:20,t:"كيف مات يهوذا الإسخريوطي (حسب إنجيل متى)؟",o:["رجموه","ضربه السيف","مضى وخنق نفسه","مات بالمرض"],c:2,l:1,r:"\"فَطَرَحَ الْفِضَّةَ فِي الْهَيْكَلِ وَانْصَرَفَ، ثُمَّ مَضَى وَخَنَقَ نَفْسَهُ.\" (متى 27: 5)"},
        {id:21,t:"ماذا كان طعام يوحنا المعمدان في البرية؟",o:["خبز وسمك","من وسلوى","جراد وعسل بري","تين وزيتون"],c:2,l:1,r:"\"وَكَانَ طَعَامُهُ جَرَادًا وَعَسَلاً بَرِّيًّا.\" (متى 3: 4)"},
        {id:22,t:"من هو التلميذ الذي لقبه الرب بـ 'صخرة'؟",o:["يوحنا","يعقوب","بطرس","أندراوس"],c:2,l:1,r:"\"أَنْتَ بُطْرُسُ، وَعَلَى هذِهِ الصَّخْرَةِ أَبْنِي كَنِيسَتِي.\" (متى 16: 18)"},
        {id:23,t:"في أي نهر اعتمد السيد المسيح؟",o:["النيل","الفرات","الأردن","دجلة"],c:2,l:1,r:"\"وَاعْتَمَدَ مِنْ يُوحَنَّا فِي الأُرْدُنِّ.\" (مرقس 1: 9)"},
        {id:24,t:"من هو الملك الذي ألقى دانيال في جب الأسود؟",o:["نبوخذنصر","داريوس","هيرودس","فرعون"],c:1,l:1,r:"\"حِينَئِذٍ أَمَرَ الْمَلِكُ... وَطَرَحُوهُ فِي جُبِّ الأُسُودِ.\" (دانيال 6: 16)"},
        {id:25,t:"من هو آخر الأنبياء الصغار في العهد القديم؟",o:["تكوين","ملاخي","رؤيا","خروج"],c:1,l:1,r:"(سفر ملاخي هو آخر أسفار الأنبياء الصغار)."},
        {id:26,t:"من هي المرأة التي تحولت إلى 'عمود ملح'؟",o:["سارة","رفقة","امرأة لوط","راحيل"],c:2,l:2,r:"\"وَنَظَرَتِ امْرَأَتُهُ مِنْ وَرَائِهِ فَصَارَتْ عَمُودَ مِلْحٍ.\" (تكوين 19: 26)"},
        {id:27,t:"من هو النبي الملقب بـ 'النبي الباكي'؟",o:["إرميا","حزقيال","إشعياء","هوشع"],c:0,l:2,r:"\"يَا لَيْتَ رَأْسِي مَاءٌ... فَأَبْكِيَ نَهَارًا وَلَيْلاً.\" (إرميا 9: 1)"},
        {id:28,t:"في أي سفر تقع قصة 'شمشون ودليلة'؟",o:["الملوك الأول","القضاة","صموئيل","راعوث"],c:1,l:2,r:"\"أَحَبَّ امْرَأَةً... اسْمُهَا دَلِيلَةُ.\" (قضاة 16: 4)"},
        {id:29,t:"من هو التلميذ الذي كان عشاراً (جابي ضرائب)؟",o:["متى","أندراوس","فيلبس","يعقوب"],c:0,l:2,r:"\"رَأَى إِنْسَانًا جَالِسًا عِنْدَ مَكَانِ الْجِبَايَةِ اسْمُهُ مَتَّى.\" (متى 9: 9)"},
        {id:30,t:"ما اسم الجبل الذي كلم الله موسى عليه (العليقة)؟",o:["الزيتون","حوريب","الكرمل","جلبوع"],c:1,l:2,r:"\"جَاءَ إِلَى جَبَلِ اللهِ حُورِيبَ.\" (خروج 3: 1)"},
        {id:31,t:"ماذا طلب الملك سليمان من الله؟",o:["مال","حكمة","عمر طويل","نصر على الأعداء"],c:1,l:2,r:"\"فَأَعْطِ عَبْدَكَ قَلْبًا فَهِيمًا لأَحْكُمَ عَلَى شَعْبِكَ.\" (ملوك الأول 3: 9)"},
        {id:32,t:"من الذي تسلق شجرة جميزة ليرى السيد المسيح؟",o:["نيقوديموس","زكا","بارتيماوس","لعازر"],c:1,l:2,r:"\"وَصَعِدَ إِلَى جُمَّيْزَةٍ لِكَيْ يَرَاهُ.\" (لوقا 19: 4)"},
        {id:33,t:"من هو أول شهيد في المسيحية (رئيس الشمامسة)؟",o:["يعقوب","بطرس","استفانوس","بولس"],c:2,l:2,r:"\"فَكَانُوا يَرْجُمُونَ اسْتِفَانُوسَ وَهُوَ يَدْعُو...\" (أعمال 7: 59)"},
        {id:34,t:"ماذا حدث لعصا هارون في خيمة الشهادة؟",o:["تحولت لحية","أفرخت وأزهرت","انكسرت","أكلت باقي العصي"],c:1,l:2,r:"\"وَإِذَا عَصَا هَارُونَ... قَدْ أَفْرَخَتْ. أَخْرَجَتْ فُرُوخًا وَأَزْهَرَتْ زَهْرًا.\" (عدد 17: 8)"},
        {id:35,t:"ما اسم حماة راعوث الموآبية؟",o:["عرفة","نعمي","سارة","مريم"],c:1,l:2,r:"\"فَرَجَعَتْ نُعْمِي وَرَاعُوثُ... كَنَّتُهَا.\" (راعوث 1: 22)"},
        {id:36,t:"كم عدد الحجارة التي أخذها داود لمواجهة جليات؟",o:["١","٣","٥","٧"],c:2,l:2,r:"\"وَانْتَخَبَ لَهُ خَمْسَةَ حِجَارَةٍ مُلْسٍ.\" (صموئيل الأول 17: 40)"},
        {id:37,t:"من هو النبي الذي صعد إلى السماء بمركبة نارية؟",o:["أليشع","إيليا","أخنوخ","موسى"],c:1,l:2,r:"\"إِذَا مَرْكَبَةٌ مِنْ نَارٍ... فَصَعِدَ إِيلِيَّا.\" (ملوك الثاني 2: 11)"},
        {id:38,t:"ما هي المدينة التي سقطت أسوارها بالهتاف والأبواق؟",o:["عاي","أريحا","شكيم","جبعون"],c:1,l:2,r:"\"فَهَتَفَ الشَّعْبُ... فَسَقَطَ السُّورُ.\" (يشوع 6: 20)"},
        {id:39,t:"من هو التلميذ الذي شك في قيامة المسيح؟",o:["بطرس","توما","يوحنا","يعقوب"],c:1,l:2,r:"\"إِنْ لَمْ أُبْصِرْ... لاَ أُومِنُ.\" (يوحنا 20: 25)"},
        {id:40,t:"من هو الشخص الذي أقامه المسيح بعد أربعة أيام من موته؟",o:["سمعان","لعازر","يوسف","يهوذا"],c:1,l:2,r:"\"لَعَازَرُ، هَلُمَّ خَارِجًا!\" (يوحنا 11: 43)"},
        {id:41,t:"ماذا يعني اسم 'عمانوئيل'؟",o:["الله محبة","الله معنا","الله يرى","الله قوي"],c:1,l:2,r:"\"عِمَّانُوئِيلَ الَّذِي تَفْسِيرُهُ: اَللهُ مَعَنَا.\" (متى 1: 23)"},
        {id:42,t:"من هما الشخصان اللذان سندا يدي موسى أثناء الحرب؟",o:["يشوع وكالب","هارون وحور","ناداب وأبيهو","إليعازر وإيثامار"],c:1,l:2,r:"\"فَأَخَذَ هَارُونُ وَحُورُ حَجَرًا... وَدَعَمَا يَدَيْهِ.\" (خروج 17: 12)"},
        {id:43,t:"في أي مدينة دعي التلاميذ 'مسيحيين' لأول مرة؟",o:["أورشليم","رومية","أنطاكية","أفسس"],c:2,l:2,r:"\"وَدُعِيَ التَّلاَمِيذُ «مَسِيحِيِّينَ» فِي أَنْطَاكِيَةَ أَوَّلاً.\" (أعمال 11: 26)"},
        {id:44,t:"كم عدد الناس الذين أطعمهم يسوع من ٥ أرغفة وسمكتين؟",o:["٣٠٠٠","٤٠٠٠","٥٠٠٠","٧٠٠٠"],c:2,l:2,r:"\"وَالآكِلُونَ كَانُوا نَحْوَ خَمْسَةِ آلاَفِ رَجُل.\" (متى 14: 21)"},
        {id:45,t:"من هو الملك الذي مزق ثيابه لما سمع كلام الشريعة؟",o:["يوشيا","آحاز","منسى","رحبعام"],c:0,l:2,r:"\"فَلَمَّا سَمِعَ الْمَلِكُ كَلاَمَ سِفْرِ الشَّرِيعَةِ مَزَّقَ ثِيَابَهُ.\" (ملوك الثاني 22: 11)"},
        {id:46,t:"ما اسم الجزيرة التي كتب فيها يوحنا سفر الرؤيا؟",o:["قبرص","كريت","بطمس","مالطة"],c:2,l:2,r:"\"فِي الْجَزِيرَةِ الَّتِي تُدْعَى بَطْمُسَ.\" (رؤيا 1: 9)"},
        {id:47,t:"من هي الملكة التي زارت سليمان لتختبر حكمته؟",o:["سبأ","إيزابيل","عثليا","أستير"],c:0,l:2,r:"\"وَسَمِعَتْ مَلِكَةُ سَبَأٍ بِخَبَرِ سُلَيْمَانَ.\" (ملوك الأول 10: 1)"},
        {id:48,t:"من هو النبي الذي أمره الله بالزواج من امرأة زنى كرمز؟",o:["هوشع","عاموس","يوئيل","حبقوق"],c:0,l:2,r:"\"خُذْ لِنَفْسِكَ امْرَأَةَ زِنًى.\" (هوشع 1: 2)"},
        {id:49,t:"في أي يوم حل الروح القدس على التلاميذ؟",o:["الفصح","المظال","يوم الخمسين","الصعود"],c:2,l:2,r:"\"وَلَمَّا حَضَرَ يَوْمُ الْخَمْسِينَ... وَامْتَلأَ الْجَمِيعُ مِنَ الرُّوحِ الْقُدُسِ.\" (أعمال 2: 1-4)"},
        {id:50,t:"ما هو أقصر أصحاح في الكتاب المقدس؟",o:["مزمور ١١٧","مزمور ٢٣","مزمور ١٥٠","يوحنا ٢"],c:0,l:2,r:"(مزمور 117 مكون من آيتين فقط)."},
        {id:51,t:"من هو القاضي الذي نذر أن يقدم 'الخارج من بيته' محرقة؟",o:["جدعون","يفتاح الجلعادي","باراق","شمشون"],c:1,l:3,r:"\"فَالْخَارِجُ الَّذِي يَخْرُجُ... يَكُونُ لِلرَّبِّ.\" (قضاة 11: 31)"},
        {id:52,t:"ما اسم والدة يوحنا المعمدان؟",o:["حنة","مريم","أليصابات","سالومة"],c:2,l:3,r:"\"وَأَمَّا أَلِيصَابَاتُ فَتَمَّ زَمَانُهَا لِتَلِدَ.\" (لوقا 1: 57)"},
        {id:53,t:"كم سنة تغرب بنو إسرائيل في مصر (حسب الخروج)؟",o:["٤٠٠","٤٣٠","٤٥٠","٤٨٠"],c:1,l:3,r:"\"فَكَانَتْ أَرْبَعَ مِئَةٍ وَثَلاَثِينَ سَنَةً.\" (خروج 12: 40)"},
        {id:54,t:"من هو الشاب الذي سقط من الطابق الثالث وأقامه بولس؟",o:["تيموثاوس","أفتيخوس","أبفرودتس","أرسترخس"],c:1,l:3,r:"\"وَكَانَ شَابٌّ اسْمُهُ أَفْتِيخُوسُ... فَسَقَطَ مِنَ الطَّبَقَةِ الثَّالِثَةِ.\" (أعمال 20: 9)"},
        {id:55,t:"ما اسم المكان الذي صارع فيه يعقوب الملاك؟",o:["بيت إيل","فنيئيل","سكوت","محنايم"],c:1,l:3,r:"\"فَدَعَا يَعْقُوبُ اسْمَ الْمَكَانِ فَنِيئِيلَ.\" (تكوين 32: 30)"},
        {id:56,t:"من هو الملك الذي طُرد وأكل العشب كالثيران؟",o:["بيلشاصر","نبوخذنصر","داريوس","كورش"],c:1,l:3,r:"\"وَأَكَلَ الْعُشْبَ كَالثِّيرَانِ.\" (دانيال 4: 33)"},
        {id:57,t:"من هو النبي الذي تنبأ عن ميلاد المسيح في 'بيت لحم أفراتة'؟",o:["إشعياء","ميخا","زكريا","ملاخي"],c:1,l:3,r:"\"أَمَّا أَنْتِ يَا بَيْتَ لَحْمِ أَفْرَاتَةَ...\" (ميخا 5: 2)"},
        {id:58,t:"ماذا كان اسم زوجة موسى؟",o:["صفورة","هاجر","قطورة","مريام"],c:0,l:3,r:"\"فَأَعْطَى مُوسَى صَفُّورَةَ ابْنَتَهُ.\" (خروج 2: 21)"},
        {id:59,t:"من هو الرسول الذي دعاه بولس 'الابن الصريح'؟",o:["تيطس","تيموثاوس","فليمون","لوقا"],c:1,l:3,r:"\"إِلَى تِيمُوثَاوُسَ، الابْنِ الصَّرِيحِ فِي الإِيمَانِ.\" (تيموثاوس الأولى 1: 2)"},
        {id:60,t:"كم عدد أمثال سليمان (حسب سفر الملوك)؟",o:["١٠٠٠","٣٠٠٠","١٠٠٥","٥٠٠٠"],c:1,l:3,r:"\"وَتَكَلَّمَ بِثَلاَثَةِ آلاَفِ مَثَل.\" (ملوك الأول 4: 32)"},
        {id:61,t:"من هو الشخص الذي 'أخذه الله' ولم يرَ الموت في سفر التكوين؟",o:["أخنوخ","متوشالح","لامك","شيث"],c:0,l:3,r:"\"وَسَارَ أَخْنُوخُ مَعَ اللهِ... لأَنَّ اللهَ أَخَذَهُ.\" (تكوين 5: 24)"},
        {id:62,t:"ما اسم معلم بولس الرسول في الناموس؟",o:["غمالائيل","قيافا","حنان","نيقوديموس"],c:0,l:3,r:"\"عِنْدَ رِجْلَيْ غَمَالاَئِيلَ.\" (أعمال 22: 3)"},
        {id:63,t:"كم كان عمر إبراهيم عندما ولد ابنه إسحاق؟",o:["٩٠","٩٩","١٠٠","١٢٠"],c:2,l:3,r:"\"وَكَانَ إِبْرَاهِيمُ ابْنَ مِئَةِ سَنَةٍ.\" (تكوين 21: 5)"},
        {id:64,t:"من هي المرأة التي قتلت 'سيسرا' قائد الجيش بالوتد؟",o:["ياعيل","راحاب","دليلة","ميكال"],c:0,l:3,r:"\"فَأَخَذَتْ يَاعِيلُ... وَتِدَ الْخَيْمَةِ.\" (قضاة 4: 21)"},
        {id:65,t:"ما هو الاسم الذي أطلقه بنو إسرائيل على الحية النحاسية؟",o:["لويثان","نحشتان","بهيموث","عزازيل"],c:1,l:3,r:"\"وَدَعَوْهَا نَحُشْتَانَ.\" (ملوك الثاني 18: 4)"},
        {id:66,t:"من هو ابن يوناثان الأعرج الذي لطف به داود؟",o:["ممفيبوشث","إيشبوشث","أبشالوم","أدونيا"],c:0,l:3,r:"\"فَجَاءَ مَفِيبُوشَثُ بْنُ يُونَاثَانَ... إِلَى دَاوُدَ.\" (صموئيل الثاني 9: 6)"},
        {id:67,t:"إلى أي سنة تعطل بناء الهيكل في سفر عزرا؟",o:["الثانية لداريوس","العشرين لأرتحششتا","٧٠ لسببي","٧ لكورش"],c:0,l:3,r:"\"إِلَى السَّنَةِ الثَّانِيَةِ مِنْ مُلْكِ دَارِيُوسَ.\" (عزرا 4: 24)"},
        {id:68,t:"من هو النبي الذي تنبأ عن 'وادي العظام اليابسة'؟",o:["إشعياء","حزقيال","إرميا","دانيال"],c:1,l:3,r:"\"وَأَنْزَلَنِي فِي وَسَطِ الْبُقْعَةِ وَهِيَ مَلآنةٌ عِظَامًا.\" (حزقيال 37: 1)"},
        {id:69,t:"ما هو اسم الملاك الذي بشر زكريا الكاهن؟",o:["ميخائيل","روفائيل","جبرائيل","أوريئيل"],c:2,l:3,r:"\"أَنَا جِبْرَائِيلُ الْوَاقِفُ قُدَّامَ اللهِ.\" (لوقا 1: 19)"},
        {id:70,t:"أين كان شاول مختبئاً عند اختياره ملكاً؟",o:["في الحرب","يحرث","بين الأمتعة","في الكهف"],c:2,l:3,r:"\"قَدِ اخْتَبَأَ بَيْنَ الأَمْتِعَةِ.\" (صموئيل الأول 10: 22)"},
        {id:71,t:"من هو القاضي الأعسر الذي قتل عجلون ملك موآب؟",o:["إهود","عثنيئيل","شمجر","يفتاح"],c:0,l:3,r:"\"أَهُودَ بْنَ جِيرَا... رَجُلاً أَعْسَرَ.\" (قضاة 3: 15)"},
        {id:72,t:"كم سنة قضاها المخلع مريضاً عند بركة حسدا؟",o:["١٢","١٨","٣٨","٤٠"],c:2,l:3,r:"\"بِهِ مَرَضٌ مُنْذُ ثَمَانٍ وَثَلاَثِينَ سَنَةً.\" (يوحنا 5: 5)"},
        {id:73,t:"إلى أي مدينة هرب يونان النبي؟",o:["صور","صيدون","ترشيش","يافا"],c:2,l:3,r:"\"لِيَهْرُبَ إِلَى تَرْشِيشَ.\" (يونان 1: 3)"},
        {id:74,t:"من هو الكاهن الذي ربى صموئيل النبي؟",o:["عالي","فينحاس","حفني","صادوق"],c:0,l:3,r:"\"وَجَاءُوا بِالصَّبِيِّ إِلَى عَالِي.\" (صموئيل الأول 1: 25)"},
        {id:75,t:"ما اسم زوجة داود الأولى (ابنة شاول)؟",o:["أبيجايل","ميكال","بثشبع","أخينوعم"],c:1,l:3,r:"\"فَأَعْطَاهُ شَاوُلُ مِيكَالَ ابْنَتَهُ.\" (صموئيل الأول 18: 27)"},
        {id:76,t:"ماذا استخدم شمجر بن عناة لقتل ٦٠٠ رجل؟",o:["سيف","منساس البقر","فك حمار","حجر المقلاع"],c:1,l:4,r:"\"فَضَرَبَ... سِتَّ مِئَةِ رَجُل بِمِنْسَاسِ الْبَقَرِ.\" (قضاة 3: 31)"},
        {id:77,t:"ما هو الاسم الآخر لـ 'تداوس' أحد الاثني عشر؟",o:["لباوس","نثنائيل","سمعان","متياس"],c:0,l:4,r:"\"وَلَبَّاوُسُ الْمُلَقَّبُ تَدَّاوُسَ.\" (متى 10: 3)"},
        {id:78,t:"من هو الذي قيل عنه 'كان جبار صيد أمام الرب'؟",o:["عيسو","نمرود","إسماعيل","شمشون"],c:1,l:4,r:"\"الَّذِي كَانَ جَبَّارَ صَيْدٍ أَمَامَ الرَّبِّ.\" (تكوين 10: 9)"},
        {id:79,t:"كم كان عمر يوشيا الملك حين ملك؟",o:["٨ سنين","١٠ سنين","١٢ سنة","٢٠ سنة"],c:0,l:4,r:"\"كَانَ يُوشِيَّا ابْنَ ثَمَانِ سِنِينَ حِينَ مَلَكَ.\" (ملوك الثاني 22: 1)"},
        {id:80,t:"من هو النبي الذي كان ساقياً للملك أرتحششتا؟",o:["نحميا","عزرا","دانيال","مردخاي"],c:0,l:4,r:"\"وَكُنْتُ سَاقِيًا لِلْمَلِكِ (أرتحششتا).\" (نحميا 1: 11)"},
        {id:81,t:"أين ذكرت الآية 'أنا أميت وأحيي. سحقت وإني أشفي'؟",o:["أيوب","مزمور","تثنية ٣٢","إشعياء"],c:2,l:4,r:"\"سَحَقْتُ وَإِنِّي أَشْفِي.\" (تثنية 32: 39)"},
        {id:82,t:"من هو المهندس الذي ملأه الله روحاً لبناء خيمة الاجتماع؟",o:["بصلئيل بن أوري","أهولياب","حور","فينحاس"],c:0,l:4,r:"\"بَصَلْئِيلَ بْنَ أُورِي... وَمَلأْتُهُ مِنْ رُوحِ اللهِ.\" (خروج 31: 2-3)"},
        {id:83,t:"كم مدينة أعطاها سليمان لحيرام ملك صور ولم تعجبه؟",o:["١٠","١٢","٢٠","٣٠"],c:2,l:4,r:"\"عِشْرِينَ مَدِينَةً... فَلَمْ تَحْسُنْ فِي عَيْنَيْهِ.\" (ملوك الأول 9: 11-12)"},
        {id:84,t:"لماذا ترك ديماس الخدمة مع بولس؟",o:["لأنه خاف","لأنه أحب العالم الحاضر","لأنه مرض","لأنه أنكر الإيمان"],c:1,l:4,r:"\"إِذْ أَحَبَّ الْعَالَمَ الْحَاضِرَ.\" (تيموثاوس الثانية 4: 10)"},
        {id:85,t:"ما اسم المذبح الذي بناه موسى بعد الانتصار على عماليق؟",o:["يهوه يرأه","يهوه نسي","يهوه شلوم","إيل بيثيل"],c:1,l:4,r:"\"وَدَعَا اسْمَهُ «يَهْوَهْ نِسِّي».\" (خروج 17: 15)"},
        {id:86,t:"من هو الملك الذي قال لبولس 'بقليل تقنعني أن أصير مسيحياً'؟",o:["فستوس","أغريباس","فيلكس","هيرودس"],c:1,l:4,r:"\"فَقَالَ أَغْرِيبَاسُ لِبُولُسَ: بِقَلِيل تُقْنِعُنِي...\" (أعمال 26: 28)"},
        {id:87,t:"كم كان طول فلك نوح (بالذراع)؟",o:["١٠٠","٣٠٠","٥٠٠","٧٠٠"],c:1,l:4,r:"\"ثَلاَثَ مِئَةِ ذِرَاعٍ يَكُونُ طُولُ الْفُلْكِ.\" (تكوين 6: 15)"},
        {id:88,t:"من الذي مات لأنه لمس تابوت العهد؟",o:["عزة","أخيو","عوبيد","ناداب"],c:0,l:4,r:"\"وَمَدَّ عُزَّةُ يَدَهُ... فَمَاتَ هُنَاكَ.\" (صموئيل الثاني 6: 7)"},
        {id:89,t:"ما اسم الصائغ الذي أثار شغباً ضد بولس في أفسس؟",o:["إسكندر","ديمتريوس","غايوس","أرسترخس"],c:1,l:4,r:"\"إِنْسَانًا اسْمُهُ دِيمِتْرِيُوسُ، صَائِغٌ.\" (أعمال 19: 24)"},
        {id:90,t:"من هو الملك الذي كان سريره من حديد وطوله ٩ أذرع؟",o:["عوج ملك باشان","سيحون","بالاق","كدرلعومر"],c:0,l:4,r:"\"إِنَّ عُوجَ... سَرِيرُهُ سَرِيرُ حَدِيدٍ... طُولُهُ تِسْعُ أَذْرُعٍ.\" (تثنية 3: 11)"},
        {id:91,t:"على أي جبل مات هارون الكاهن؟",o:["نبو","هور","سيناء","الزيتون"],c:1,l:4,r:"\"وَمَاتَ هَارُونُ هُنَاكَ عَلَى رَأْسِ الْجَبَلِ (هور).\" (عدد 20: 28)"},
        {id:92,t:"ما هو لون الفرس الثالث في سفر الرؤيا؟",o:["أبيض","أحمر","أسود","أخضر"],c:2,l:4,r:"\"وَإِذَا فَرَسٌ أَسْوَدُ، وَالْجَالِسُ عَلَيْهِ مَعَهُ مِيزَانٌ.\" (رؤيا 6: 5)"},
        {id:93,t:"من النبي الذي تنبأ عن المسيح قائلاً 'جروح في بيت أحبائي'؟",o:["إشعياء","إرميا","زكريا","ملاخي"],c:2,l:4,r:"\"جُرِحْتُ بِهَا فِي بَيْتِ أَحِبَّائِي.\" (زكريا 13: 6)"},
        {id:94,t:"من هو الشخص المذكور في الكتاب المقدس أنه كان 'على الجمال' لداود؟",o:["أوبيل الإسماعيلي","يازيز","شمعي","بعل"],c:0,l:4,r:"\"وَعَلَى الْجِمَالِ أُوبِيلُ الإِسْمَاعِيلِيُّ.\" (أخبار الأول 27: 30)"},
        {id:95,t:"ما هو الاسم العبري للمكان الذي جلس فيه بيلاطس للقضاء (البلاط)؟",o:["جلجثة","جباثا","حقل دما","جثسيماني"],c:1,l:4,r:"\"يُقَالُ لَهُ البَلاَطُ وَبِالْعِبْرَانِيَّةِ جَبَّاثَا.\" (يوحنا 19: 13)"},
        {id:96,t:"من هو النبي الذي أمره الله أن يطبخ طعامه على خرء البقر؟",o:["حزقيال","إرميا","دانيال","هوشع"],c:0,l:4,r:"\"جَعَلْتُ لَكَ خِثْيَ الْبَقَرِ بَدَلَ خُرْءِ الإِنْسَانِ.\" (حزقيال 4: 15)"},
        {id:97,t:"كم عدد مدن الملجأ التي عينها يشوع؟",o:["٣","٦","١٠","١٢"],c:1,l:4,r:"\"وَقَدَّسُوا قَادَشَ... وَشَكِيمَ... وَقَرْيَةَ أَرْبَعَ...\" (يشوع 20)."},
        {id:98,t:"من هو البطل الذي قتل ٨٠٠ رجل بضربة واحدة؟",o:["يوشيب (عدينو)","أليعازر","شمة","أبشاي"],c:0,l:4,r:"\"هَزَّ رُمْحَهُ عَلَى ثَمَانِ مِئَةٍ قَتَلَهُمْ.\" (صموئيل الثاني 23: 8)"},
        {id:99,t:"من هو الملك الذي حكم إسرائيل ٧ أيام فقط؟",o:["زمري","عمري","تيبني","ناداب"],c:0,l:4,r:"\"مَلَكَ زِمْرِي سَبْعَةَ أَيَّامٍ فِي تِرْصَةَ.\" (ملوك الأول 16: 15)"},
        {id:100,t:"ما هو اسم أم داود النبي؟",o:["لم يذكر في الكتاب المقدس","نِتْسِيبَت","حزيلل","مريم"],c:0,l:4,r:"(لا يوجد نص صريح يذكر اسم أم داود في الكتاب المقدس)."}
    ],

        // ==========================================
    // ENGLISH (Full 100 Questions - NKJV)
    // ==========================================
    en: [
        {id:1, t:"Who was the prophet swallowed by a great fish?", o:["Moses","Jonah","Isaiah","Daniel"], c:1, l:1, r:"\"Now the LORD had prepared a great fish to swallow Jonah.\" (Jonah 1:17)"},
        {id:2, t:"How many tribes of Israel were there?", o:["7","10","12","40"], c:2, l:1, r:"\"All these are the twelve tribes of Israel.\" (Genesis 49:28)"},
        {id:3, t:"In which city was the Lord Christ born?", o:["Nazareth","Jerusalem","Bethlehem","Capernaum"], c:2, l:1, r:"\"Now after Jesus was born in Bethlehem of Judea...\" (Matthew 2:1)"},
        {id:4, t:"What is the first book of the Bible?", o:["Exodus","Genesis","Psalms","Revelation"], c:1, l:1, r:"\"In the beginning God created the heavens and the earth.\" (Genesis 1:1)"},
        {id:5, t:"Which disciple denied the Lord Christ three times?", o:["Judas Iscariot","John the Beloved","Peter the Apostle","Thomas the Doubter"], c:2, l:1, r:"\"And Peter remembered the word of Jesus... 'you will deny Me three times.'\" (Matthew 26:75)"},
        {id:6, t:"What did God create on the fourth day?", o:["Light","The Firmament","Sun, Moon, and Stars","Birds and Fish"], c:2, l:1, r:"\"Then God made two great lights... He made the stars also.\" (Genesis 1:16)"},
        {id:7, t:"Who lived the longest life in the Bible?", o:["Noah","Adam","Methuselah","Abraham"], c:2, l:1, r:"\"So all the days of Methuselah were nine hundred and sixty-nine years.\" (Genesis 5:27)"},
        {id:8, t:"What was David's job before becoming King?", o:["Carpenter","Shepherd","Fisherman","Tax Collector"], c:1, l:1, r:"\"There remains yet the youngest, and there he is, keeping the sheep.\" (1 Samuel 16:11)"},
        {id:9, t:"How many days did the Lord Christ fast in the wilderness?", o:["3 days","7 days","30 days","40 days"], c:3, l:1, r:"\"And when He had fasted forty days and forty nights, afterward He was hungry.\" (Matthew 4:2)"},
        {id:10, t:"Who was commanded by God to build the Ark?", o:["Abraham","Moses","Noah","Jacob"], c:2, l:1, r:"\"Make yourself an ark of gopherwood.\" (Genesis 6:14)"},
        {id:11, t:"Who was the boy that defeated the giant Goliath?", o:["Saul","Jonathan","David","Samson"], c:2, l:1, r:"\"So David prevailed over the Philistine with a sling and a stone.\" (1 Samuel 17:50)"},
        {id:12, t:"What is the name of the first human created by God?", o:["Noah","Abraham","Adam","Cain"], c:2, l:1, r:"\"And the LORD God formed man of the dust of the ground.\" (Genesis 2:7)"},
        {id:13, t:"What was the first miracle performed by the Lord Christ?", o:["Walking on water","Turning water into wine","Healing a leper","Feeding the multitude"], c:1, l:1, r:"\"This beginning of signs Jesus did in Cana of Galilee.\" (John 2:11)"},
        {id:14, t:"Which prophet received the Ten Commandments?", o:["Abraham","Isaac","Jacob","Moses"], c:3, l:1, r:"\"He gave Moses... two tablets of the Testimony.\" (Exodus 31:18)"},
        {id:15, t:"How many canonical Gospels are in the New Testament?", o:["3","4","5","6"], c:1, l:1, r:"(Matthew, Mark, Luke, John)."},
        {id:16, t:"What sign did God give Noah after the flood?", o:["Pillar of fire","Rainbow","The Star","Burning bush"], c:1, l:1, r:"\"I set My rainbow in the cloud, and it shall be for the sign of the covenant...\" (Genesis 9:13)"},
        {id:17, t:"Who was sold by his brothers to the Ishmaelites?", o:["Benjamin","Joseph","Reuben","Levi"], c:1, l:1, r:"\"So they sold Joseph to the Ishmaelites... and they took Joseph to Egypt.\" (Genesis 37:28)"},
        {id:18, t:"What is the shortest verse in the Bible?", o:["God is love","Rejoice","Jesus wept","Pray without ceasing"], c:2, l:1, r:"\"Jesus wept.\" (John 11:35)"},
        {id:19, t:"Who is the woman who prayed for a son and God gave her Samuel?", o:["Hannah","Peninnah","Rachel","Leah"], c:0, l:1, r:"\"So she called his name Samuel, saying, 'Because I have asked for him from the LORD.'\" (1 Samuel 1:20)"},
        {id:20, t:"How did Judas Iscariot die (according to Matthew)?", o:["Stoned","Struck by a sword","Went and hanged himself","Died of illness"], c:2, l:1, r:"\"Then he threw down the pieces of silver... and went and hanged himself.\" (Matthew 27:5)"},
        {id:21, t:"What was John the Baptist's food in the wilderness?", o:["Bread and fish","Manna and quail","Locusts and wild honey","Figs and olives"], c:2, l:1, r:"\"His food was locusts and wild honey.\" (Matthew 3:4)"},
        {id:22, t:"Which disciple did the Lord name 'The Rock'?", o:["John","James","Peter","Andrew"], c:2, l:1, r:"\"And I also say to you that you are Peter, and on this rock I will build My church.\" (Matthew 16:18)"},
        {id:23, t:"In which river was the Lord Christ baptized?", o:["The Nile","The Euphrates","The Jordan","The Tigris"], c:2, l:1, r:"\"And was baptized by John in the Jordan.\" (Mark 1:9)"},
        {id:24, t:"Who was the King that threw Daniel into the lions' den?", o:["Nebuchadnezzar","Darius","Herod","Pharaoh"], c:1, l:1, r:"\"So the king gave the command, and they brought Daniel and cast him into the den of lions.\" (Daniel 6:16)"},
        {id:25, t:"Who is the last of the Minor Prophets in the Old Testament?", o:["Genesis","Malachi","Revelation","Exodus"], c:1, l:1, r:"(The Book of Malachi is the last book of the Minor Prophets)."},
        {id:26, t:"Who was the woman turned into a 'pillar of salt'?", o:["Sarah","Rebekah","Lot's wife","Rachel"], c:2, l:2, r:"\"But his wife looked back behind him, and she became a pillar of salt.\" (Genesis 19:26)"},
        {id:27, t:"Which prophet is known as the 'Weeping Prophet'?", o:["Jeremiah","Ezekiel","Isaiah","Hosea"], c:0, l:2, r:"\"Oh, that my head were waters... That I might weep day and night.\" (Jeremiah 9:1)"},
        {id:28, t:"In which book is the story of 'Samson and Delilah' found?", o:["1 Kings","Judges","Samuel","Ruth"], c:1, l:2, r:"\"He loved a woman... whose name was Delilah.\" (Judges 16:4)"},
        {id:29, t:"Which disciple was a tax collector?", o:["Matthew","Andrew","Philip","James"], c:0, l:2, r:"\"He saw a man named Matthew sitting at the tax office.\" (Matthew 9:9)"},
        {id:30, t:"What is the name of the mountain where God spoke to Moses (Burning Bush)?", o:["Olives","Horeb","Carmel","Gilboa"], c:1, l:2, r:"\"And came to Horeb, the mountain of God.\" (Exodus 3:1)"},
        {id:31, t:"What did King Solomon ask from God?", o:["Wealth","Wisdom","Long life","Victory over enemies"], c:1, l:2, r:"\"Therefore give to Your servant an understanding heart to judge Your people.\" (1 Kings 3:9)"},
        {id:32, t:"Who climbed a sycamore tree to see the Lord Christ?", o:["Nicodemus","Zacchaeus","Bartimaeus","Lazarus"], c:1, l:2, r:"\"So he ran ahead and climbed up into a sycamore tree to see Him.\" (Luke 19:4)"},
        {id:33, t:"Who was the first martyr in Christianity (The Archdeacon)?", o:["James","Peter","Stephen","Paul"], c:2, l:2, r:"\"And they stoned Stephen as he was calling on God...\" (Acts 7:59)"},
        {id:34, t:"What happened to Aaron's rod in the Tabernacle of Witness?", o:["Turned into a serpent","Budded and blossomed","Broke","Ate the other rods"], c:1, l:2, r:"\"The rod of Aaron... had sprouted and put forth buds, had produced blossoms.\" (Numbers 17:8)"},
        {id:35, t:"What was the name of Ruth the Moabitess's mother-in-law?", o:["Orpah","Naomi","Sarah","Mary"], c:1, l:2, r:"\"So Naomi returned, and Ruth... her daughter-in-law with her.\" (Ruth 1:22)"},
        {id:36, t:"How many stones did David take to face Goliath?", o:["1","3","5","7"], c:2, l:2, r:"\"And chose for himself five smooth stones from the brook.\" (1 Samuel 17:40)"},
        {id:37, t:"Who is the prophet that went up to heaven in a chariot of fire?", o:["Elisha","Elijah","Enoch","Moses"], c:1, l:2, r:"\"There appeared a chariot of fire... and Elijah went up.\" (2 Kings 2:11)"},
        {id:38, t:"Which city's walls fell down after shouting and blowing trumpets?", o:["Ai","Jericho","Shechem","Gibeon"], c:1, l:2, r:"\"So the people shouted... and the wall fell down flat.\" (Joshua 6:20)"},
        {id:39, t:"Which disciple doubted the resurrection of Christ?", o:["Peter","Thomas","John","James"], c:1, l:2, r:"\"Unless I see... I will not believe.\" (John 20:25)"},
        {id:40, t:"Who did Christ raise from the dead after four days?", o:["Simon","Lazarus","Joseph","Judas"], c:1, l:2, r:"\"Lazarus, come forth!\" (John 11:43)"},
        {id:41, t:"What does the name 'Immanuel' mean?", o:["God is love","God with us","God sees","God is strong"], c:1, l:2, r:"\"Immanuel, which is translated, 'God with us'.\" (Matthew 1:23)"},
        {id:42, t:"Who were the two men who supported Moses' hands during the battle?", o:["Joshua and Caleb","Aaron and Hur","Nadab and Abihu","Eleazar and Ithamar"], c:1, l:2, r:"\"Aaron and Hur supported his hands.\" (Exodus 17:12)"},
        {id:43, t:"In which city were the disciples called 'Christians' for the first time?", o:["Jerusalem","Rome","Antioch","Ephesus"], c:2, l:2, r:"\"And the disciples were first called Christians in Antioch.\" (Acts 11:26)"},
        {id:44, t:"How many people did Jesus feed with 5 loaves and 2 fish?", o:["3000","4000","5000","7000"], c:2, l:2, r:"\"Now those who had eaten were about five thousand men.\" (Matthew 14:21)"},
        {id:45, t:"Which King tore his clothes when he heard the Book of the Law?", o:["Josiah","Ahaz","Manasseh","Rehoboam"], c:0, l:2, r:"\"Now it happened, when the king heard the words of the Book of the Law, that he tore his clothes.\" (2 Kings 22:11)"},
        {id:46, t:"What is the name of the island where John wrote Revelation?", o:["Cyprus","Crete","Patmos","Malta"], c:2, l:2, r:"\"I... was on the island that is called Patmos.\" (Revelation 1:9)"},
        {id:47, t:"Which Queen visited Solomon to test his wisdom?", o:["Sheba","Jezebel","Athaliah","Esther"], c:0, l:2, r:"\"Now when the queen of Sheba heard of the fame of Solomon...\" (1 Kings 10:1)"},
        {id:48, t:"Which prophet was commanded to marry a harlot as a symbol?", o:["Hosea","Amos","Joel","Habakkuk"], c:0, l:2, r:"\"Go, take yourself a wife of harlotry.\" (Hosea 1:2)"},
        {id:49, t:"On which day did the Holy Spirit descend upon the disciples?", o:["Passover","Tabernacles","Pentecost","Ascension"], c:2, l:2, r:"\"When the Day of Pentecost had fully come... And they were all filled with the Holy Spirit.\" (Acts 2:1-4)"},
        {id:50, t:"What is the shortest chapter in the Bible?", o:["Psalm 117","Psalm 23","Psalm 150","John 2"], c:0, l:2, r:"(Psalm 117 consists of only two verses)."},
        {id:51, t:"Who was the Judge who vowed to offer 'whatever comes out of his house' as a burnt offering?", o:["Gideon","Jephthah the Gileadite","Barak","Samson"], c:1, l:3, r:"\"Then it shall be... I will offer it up as a burnt offering.\" (Judges 11:31)"},
        {id:52, t:"What was the name of John the Baptist's mother?", o:["Hannah","Mary","Elizabeth","Salome"], c:2, l:3, r:"\"Now Elizabeth's full time came for her to be delivered.\" (Luke 1:57)"},
        {id:53, t:"How many years did the children of Israel dwell in Egypt (According to Exodus)?", o:["400","430","450","480"], c:1, l:3, r:"\"Now the sojourn... was four hundred and thirty years.\" (Exodus 12:40)"},
        {id:54, t:"Who was the young man who fell from the third story and Paul raised him?", o:["Timothy","Eutychus","Epaphroditus","Aristarchus"], c:1, l:3, r:"\"And a certain young man named Eutychus... fell down from the third story.\" (Acts 20:9)"},
        {id:55, t:"What is the name of the place where Jacob wrestled with the Angel?", o:["Bethel","Peniel","Succoth","Mahanaim"], c:1, l:3, r:"\"So Jacob called the name of the place Peniel.\" (Genesis 32:30)"},
        {id:56, t:"Which King was driven away and ate grass like oxen?", o:["Belshazzar","Nebuchadnezzar","Darius","Cyrus"], c:1, l:3, r:"\"And he ate grass like oxen.\" (Daniel 4:33)"},
        {id:57, t:"Which prophet prophesied Christ's birth in 'Bethlehem Ephrathah'?", o:["Isaiah","Micah","Zechariah","Malachi"], c:1, l:3, r:"\"But you, Bethlehem Ephrathah...\" (Micah 5:2)"},
        {id:58, t:"What was the name of Moses' wife?", o:["Zipporah","Hagar","Keturah","Miriam"], c:0, l:3, r:"\"And he gave Moses Zipporah his daughter.\" (Exodus 2:21)"},
        {id:59, t:"Which apostle did Paul call 'my true son in the faith'?", o:["Titus","Timothy","Philemon","Luke"], c:1, l:3, r:"\"To Timothy, a true son in the faith.\" (1 Timothy 1:2)"},
        {id:60, t:"How many proverbs did Solomon speak (According to 1 Kings)?", o:["1000","3000","1005","5000"], c:1, l:3, r:"\"He spoke three thousand proverbs.\" (1 Kings 4:32)"},
        {id:61, t:"Who is the person who 'God took' and did not see death in Genesis?", o:["Enoch","Methuselah","Lamech","Seth"], c:0, l:3, r:"\"And Enoch walked with God... for God took him.\" (Genesis 5:24)"},
        {id:62, t:"What is the name of the teacher who taught Paul the Law?", o:["Gamaliel","Caiaphas","Annas","Nicodemus"], c:0, l:3, r:"\"At the feet of Gamaliel.\" (Acts 22:3)"},
        {id:63, t:"How old was Abraham when his son Isaac was born?", o:["90","99","100","120"], c:2, l:3, r:"\"Now Abraham was one hundred years old.\" (Genesis 21:5)"},
        {id:64, t:"Who is the woman who killed 'Sisera' the commander with a tent peg?", o:["Jael","Rahab","Delilah","Michal"], c:0, l:3, r:"\"Then Jael... took a tent peg.\" (Judges 4:21)"},
        {id:65, t:"What name did the children of Israel give to the bronze serpent?", o:["Leviathan","Nehushtan","Behemoth","Azazel"], c:1, l:3, r:"\"For... they called it Nehushtan.\" (2 Kings 18:4)"},
        {id:66, t:"Who was Jonathan's lame son to whom David showed kindness?", o:["Mephibosheth","Ishbosheth","Absalom","Adonijah"], c:0, l:3, r:"\"Mephibosheth the son of Jonathan... came to David.\" (2 Samuel 9:6)"},
        {id:67, t:"Until which year did the construction of the temple cease in Ezra?", o:["2nd year of Darius","20th of Artaxerxes","70th of captivity","7th of Cyrus"], c:0, l:3, r:"\"Until the second year of the reign of Darius.\" (Ezra 4:24)"},
        {id:68, t:"Which prophet prophesied about the 'Valley of Dry Bones'?", o:["Isaiah","Ezekiel","Jeremiah","Daniel"], c:1, l:3, r:"\"Set me down in the midst of the valley; and it was full of bones.\" (Ezekiel 37:1)"},
        {id:69, t:"What is the name of the angel who brought good news to Zacharias?", o:["Michael","Raphael","Gabriel","Uriel"], c:2, l:3, r:"\"I am Gabriel, who stands in the presence of God.\" (Luke 1:19)"},
        {id:70, t:"Where was Saul hiding when he was chosen as King?", o:["In battle","Plowing","Among the equipment","In a cave"], c:2, l:3, r:"\"He has hidden himself among the equipment.\" (1 Samuel 10:22)"},
        {id:71, t:"Who was the left-handed Judge who killed Eglon king of Moab?", o:["Ehud","Othniel","Shamgar","Jephthah"], c:0, l:3, r:"\"Ehud the son of Gera... a left-handed man.\" (Judges 3:15)"},
        {id:72, t:"How many years had the paralytic been ill at the pool of Bethesda?", o:["12","18","38","40"], c:2, l:3, r:"\"Now a certain man was there who had an infirmity thirty-eight years.\" (John 5:5)"},
        {id:73, t:"To which city did Jonah flee?", o:["Tyre","Sidon","Tarshish","Jaffa"], c:2, l:3, r:"\"To flee to Tarshish.\" (Jonah 1:3)"},
        {id:74, t:"Who was the priest who raised the prophet Samuel?", o:["Eli","Phinehas","Hophni","Zadok"], c:0, l:3, r:"\"And they brought the child to Eli.\" (1 Samuel 1:25)"},
        {id:75, t:"What was the name of David's first wife (Saul's daughter)?", o:["Abigail","Michal","Bathsheba","Ahinoam"], c:1, l:3, r:"\"And Saul gave him Michal his daughter.\" (1 Samuel 18:27)"},
        {id:76, t:"What did Shamgar son of Anath use to kill 600 men?", o:["Sword","Ox goad","Donkey's jawbone","Sling stone"], c:1, l:4, r:"\"He also killed six hundred men of the Philistines with an ox goad.\" (Judges 3:31)"},
        {id:77, t:"What is the other name for 'Thaddaeus' one of the twelve?", o:["Lebbaeus","Nathanael","Simon","Matthias"], c:0, l:4, r:"\"Lebbaeus, whose surname was Thaddaeus.\" (Matthew 10:3)"},
        {id:78, t:"Who was described as 'a mighty hunter before the Lord'?", o:["Esau","Nimrod","Ishmael","Samson"], c:1, l:4, r:"\"He was a mighty hunter before the LORD.\" (Genesis 10:9)"},
        {id:79, t:"How old was King Josiah when he became king?", o:["8 years","10 years","12 years","20 years"], c:0, l:4, r:"\"Josiah was eight years old when he became king.\" (2 Kings 22:1)"},
        {id:80, t:"Which prophet was the cupbearer to King Artaxerxes?", o:["Nehemiah","Ezra","Daniel","Mordecai"], c:0, l:4, r:"\"For I was the king's cupbearer.\" (Nehemiah 1:11)"},
        {id:81, t:"Where is the verse 'I kill and I make alive; I wound and I heal' found?", o:["Job","Psalms","Deuteronomy 32","Isaiah"], c:2, l:4, r:"\"I wound and I heal.\" (Deuteronomy 32:39)"},
        {id:82, t:"Who was the craftsman filled with the Spirit to build the Tabernacle?", o:["Bezalel son of Uri","Aholiab","Hur","Phinehas"], c:0, l:4, r:"\"Bezalel the son of Uri... and I have filled him with the Spirit of God.\" (Exodus 31:2-3)"},
        {id:83, t:"How many cities did Solomon give to Hiram which did not please him?", o:["10","12","20","30"], c:2, l:4, r:"\"Twenty cities... and they did not please him.\" (1 Kings 9:11-12)"},
        {id:84, t:"Why did Demas forsake Paul?", o:["He was afraid","He loved this present world","He was sick","He denied the faith"], c:1, l:4, r:"\"For Demas has forsaken me, having loved this present world.\" (2 Timothy 4:10)"},
        {id:85, t:"What was the name of the altar Moses built after defeating Amalek?", o:["Jehovah Jireh","Jehovah Nissi","Jehovah Shalom","El Bethel"], c:1, l:4, r:"\"And called its name The-LORD-Is-My-Banner (Jehovah Nissi).\" (Exodus 17:15)"},
        {id:86, t:"Who was the King who told Paul 'You almost persuade me to become a Christian'?", o:["Festus","Agrippa","Felix","Herod"], c:1, l:4, r:"\"Then Agrippa said to Paul, 'You almost persuade me to become a Christian.'\" (Acts 26:28)"},
        {id:87, t:"How long was Noah's Ark (in cubits)?", o:["100","300","500","700"], c:1, l:4, r:"\"The length of the ark shall be three hundred cubits.\" (Genesis 6:15)"},
        {id:88, t:"Who died because he touched the Ark of the Covenant?", o:["Uzzah","Ahio","Obed","Nadab"], c:0, l:4, r:"\"And Uzzah put out his hand... and died there.\" (2 Samuel 6:7)"},
        {id:89, t:"What was the name of the silversmith who caused a riot in Ephesus?", o:["Alexander","Demetrius","Gaius","Aristarchus"], c:1, l:4, r:"\"For a certain man named Demetrius, a silversmith.\" (Acts 19:24)"},
        {id:90, t:"Which King had a bedstead of iron 9 cubits long?", o:["Og king of Bashan","Sihon","Balak","Chedorlaomer"], c:0, l:4, r:"\"For only Og... his bedstead was an iron bedstead... nine cubits is its length.\" (Deuteronomy 3:11)"},
        {id:91, t:"On which mountain did Aaron the priest die?", o:["Nebo","Hor","Sinai","Olives"], c:1, l:4, r:"\"And Aaron died there on the top of the mountain (Hor).\" (Numbers 20:28)"},
        {id:92, t:"What was the color of the third horse in Revelation?", o:["White","Red","Black","Green"], c:2, l:4, r:"\"And behold, a black horse, and he who sat on it had a pair of scales.\" (Revelation 6:5)"},
        {id:93, t:"Which prophet prophesied about Christ saying 'Wounded in the house of my friends'?", o:["Isaiah","Jeremiah","Zechariah","Malachi"], c:2, l:4, r:"\"Those with which I was wounded in the house of my friends.\" (Zechariah 13:6)"},
        {id:94, t:"Who is the person mentioned as being 'over the camels' for David?", o:["Obil the Ishmaelite","Jaziz","Shimei","Baal"], c:0, l:4, r:"\"Over the camels was Obil the Ishmaelite.\" (1 Chronicles 27:30)"},
        {id:95, t:"What is the Hebrew name for the place where Pilate sat for judgment (The Pavement)?", o:["Golgotha","Gabbatha","Akeldama","Gethsemane"], c:1, l:4, r:"\"Called The Pavement, but in Hebrew, Gabbatha.\" (John 19:13)"},
        {id:96, t:"Which prophet was commanded to cook his food over cow's dung?", o:["Ezekiel","Jeremiah","Daniel","Hosea"], c:0, l:4, r:"\"I have given you cow's dung instead of human waste.\" (Ezekiel 4:15)"},
        {id:97, t:"How many cities of refuge did Joshua appoint?", o:["3","6","10","12"], c:1, l:4, r:"\"And they appointed Kedesh... Shechem... Kirjath Arba...\" (Joshua 20 - Total 6)."},
        {id:98, t:"Who is the mighty man who killed 800 men at one time?", o:["Josheb-Basshebeth (Adino)","Eleazar","Shammah","Abishai"], c:0, l:4, r:"\"He killed eight hundred men at one time.\" (2 Samuel 23:8)"},
        {id:99, t:"Which King reigned over Israel for only 7 days?", o:["Zimri","Omri","Tibni","Nadab"], c:0, l:4, r:"\"Zimri had reigned seven days in Tirzah.\" (1 Kings 16:15)"},
        {id:100, t:"What is the name of David's mother?", o:["Not mentioned in the Bible","Nitzevet","Hazlelponi","Mary"], c:0, l:4, r:"(There is no explicit text naming David's mother in the Bible)."}
    ],

    // ==========================================
    // FRENCH (Full 100 Questions - Louis Segond)
    // ==========================================
    fr: [
        {id:1, t:"Quel prophète a été avalé par un grand poisson ?", o:["Moïse","Jonas","Ésaïe","Daniel"], c:1, l:1, r:"\"L'Éternel fit venir un grand poisson pour engloutir Jonas.\" (Jonas 1:17)"},
        {id:2, t:"Combien y a-t-il de tribus d'Israël ?", o:["7","10","12","40"], c:2, l:1, r:"\"Ce sont là tous ceux qui forment les douze tribus d'Israël.\" (Genèse 49:28)"},
        {id:3, t:"Dans quelle ville le Seigneur Jésus est-il né ?", o:["Nazareth","Jérusalem","Bethléhem","Capharnaüm"], c:2, l:1, r:"\"Jésus étant né à Bethléhem en Judée...\" (Matthieu 2:1)"},
        {id:4, t:"Quel est le premier livre de la Bible ?", o:["Exode","Genèse","Psaumes","Apocalypse"], c:1, l:1, r:"\"Au commencement, Dieu créa les cieux et la terre.\" (Genèse 1:1)"},
        {id:5, t:"Quel disciple a renié le Seigneur trois fois ?", o:["Judas Iscariot","Jean le Bien-aimé","Pierre l'Apôtre","Thomas"], c:2, l:1, r:"\"Et Pierre se souvint... tu me renieras trois fois.\" (Matthieu 26:75)"},
        {id:6, t:"Qu'est-ce que Dieu a créé le quatrième jour ?", o:["La lumière","L'étendue","Soleil, Lune et Étoiles","Oiseaux et Poissons"], c:2, l:1, r:"\"Dieu fit les deux grands luminaires... il fit aussi les étoiles.\" (Genèse 1:16)"},
        {id:7, t:"Qui a vécu le plus longtemps dans la Bible ?", o:["Noé","Adam","Mathusalem","Abraham"], c:2, l:1, r:"\"Tous les jours de Metuschélah furent de neuf cent soixante-neuf ans.\" (Genèse 5:27)"},
        {id:8, t:"Quel était le métier de David avant de devenir roi ?", o:["Charpentier","Berger","Pêcheur","Collecteur d'impôts"], c:1, l:1, r:"\"Il reste encore le plus jeune, mais il fait paître les brebis.\" (1 Samuel 16:11)"},
        {id:9, t:"Combien de jours Jésus a-t-il jeûné dans le désert ?", o:["3 jours","7 jours","30 jours","40 jours"], c:3, l:1, r:"\"Après avoir jeûné quarante jours et quarante nuits, il eut faim.\" (Matthieu 4:2)"},
        {id:10, t:"Qui a reçu l'ordre de Dieu de construire l'Arche ?", o:["Abraham","Moïse","Noé","Jacob"], c:2, l:1, r:"\"Fais-toi une arche de bois de gopher.\" (Genèse 6:14)"},
        {id:11, t:"Qui est le jeune homme qui a vaincu le géant Goliath ?", o:["Saül","Jonathan","David","Samson"], c:2, l:1, r:"\"Ainsi, avec une fronde et une pierre, David fut plus fort que le Philistin.\" (1 Samuel 17:50)"},
        {id:12, t:"Quel est le nom du premier homme créé par Dieu ?", o:["Noé","Abraham","Adam","Caïn"], c:2, l:1, r:"\"L'Éternel Dieu forma l'homme de la poussière de la terre.\" (Genèse 2:7)"},
        {id:13, t:"Quel fut le premier miracle accompli par le Seigneur Jésus ?", o:["Marcher sur l'eau","Changer l'eau en vin","Guérir un lépreux","Nourrir la foule"], c:1, l:1, r:"\"Tel fut, à Cana en Galilée, le premier des miracles que fit Jésus.\" (Jean 2:11)"},
        {id:14, t:"Quel prophète a reçu les Dix Commandements ?", o:["Abraham","Isaac","Jacob","Moïse"], c:3, l:1, r:"\"Il donna à Moïse... les deux tables du témoignage.\" (Exode 31:18)"},
        {id:15, t:"Combien d'Évangiles canoniques y a-t-il dans le Nouveau Testament ?", o:["3","4","5","6"], c:1, l:1, r:"(Matthieu, Marc, Luc, Jean)."},
        {id:16, t:"Quel signe Dieu a-t-il donné à Noé après le déluge ?", o:["Colonne de feu","Arc-en-ciel","L'Étoile","Buisson ardent"], c:1, l:1, r:"\"J'ai placé mon arc dans la nue, et il servira de signe d'alliance...\" (Genèse 9:13)"},
        {id:17, t:"Qui a été vendu par ses frères aux Ismaélites ?", o:["Benjamin","Joseph","Ruben","Lévi"], c:1, l:1, r:"\"Ils vendirent Joseph aux Ismaélites... et ils emmenèrent Joseph en Égypte.\" (Genèse 37:28)"},
        {id:18, t:"Quel est le verset le plus court de la Bible ?", o:["Dieu est amour","Réjouissez-vous","Jésus pleura","Priez sans cesse"], c:2, l:1, r:"\"Jésus pleura.\" (Jean 11:35)"},
        {id:19, t:"Quelle femme a prié pour un fils et Dieu lui a donné Samuel ?", o:["Anne","Peninna","Rachel","Léa"], c:0, l:1, r:"\"Elle lui donna le nom de Samuel, car, dit-elle, je l'ai demandé à l'Éternel.\" (1 Samuel 1:20)"},
        {id:20, t:"Comment Judas Iscariot est-il mort (selon Matthieu) ?", o:["Lapidé","Frappé par l'épée","Il s'est pendu","Maladie"], c:2, l:1, r:"\"Il jeta les pièces d'argent... et alla se pendre.\" (Matthieu 27:5)"},
        {id:21, t:"Quelle était la nourriture de Jean-Baptiste dans le désert ?", o:["Pain et poisson","Manne et cailles","Sauterelles et miel","Figues et olives"], c:2, l:1, r:"\"Sa nourriture était des sauterelles et du miel sauvage.\" (Matthieu 3:4)"},
        {id:22, t:"Quel disciple le Seigneur a-t-il appelé 'le Roc' (Pierre) ?", o:["Jean","Jacques","Pierre","André"], c:2, l:1, r:"\"Et moi, je te dis que tu es Pierre, et que sur cette pierre je bâtirai mon Église.\" (Matthieu 16:18)"},
        {id:23, t:"Dans quel fleuve le Seigneur Jésus a-t-il été baptisé ?", o:["Le Nil","L'Euphrate","Le Jourdain","Le Tigre"], c:2, l:1, r:"\"Jésus... fut baptisé par Jean dans le Jourdain.\" (Marc 1:9)"},
        {id:24, t:"Quel roi a jeté Daniel dans la fosse aux lions ?", o:["Nabuchodonosor","Darius","Hérode","Pharaon"], c:1, l:1, r:"\"Alors le roi donna l'ordre qu'on amenât Daniel, et qu'on le jetât dans la fosse aux lions.\" (Daniel 6:16)"},
        {id:25, t:"Quel est le dernier des 'Petits Prophètes' dans l'Ancien Testament ?", o:["Genèse","Malachie","Apocalypse","Exode"], c:1, l:1, r:"(Le livre de Malachie est le dernier livre des prophètes)."},
        {id:26, t:"Quelle femme a été changée en 'statue de sel' ?", o:["Sara","Rebecca","La femme de Lot","Rachel"], c:2, l:2, r:"\"La femme de Lot regarda en arrière, et elle devint une statue de sel.\" (Genèse 19:26)"},
        {id:27, t:"Quel prophète est appelé le 'Prophète qui pleure' ?", o:["Jérémie","Ézéchiel","Ésaïe","Osée"], c:0, l:2, r:"\"Oh ! si ma tête était remplie d'eau... Je pleurerais jour et nuit.\" (Jérémie 9:1)"},
        {id:28, t:"Dans quel livre trouve-t-on l'histoire de 'Samson et Dalila' ?", o:["1 Rois","Juges","Samuel","Ruth"], c:1, l:2, r:"\"Il aima une femme... nommée Dalila.\" (Juges 16:4)"},
        {id:29, t:"Quel disciple était collecteur d'impôts (péager) ?", o:["Matthieu","André","Philippe","Jacques"], c:0, l:2, r:"\"Il vit un homme, nommé Matthieu, assis au bureau des péages.\" (Matthieu 9:9)"},
        {id:30, t:"Quel est le nom de la montagne où Dieu a parlé à Moïse (Buisson ardent) ?", o:["Oliviers","Horeb","Carmel","Guilboa"], c:1, l:2, r:"\"Il mena le troupeau... et vint à la montagne de Dieu, à Horeb.\" (Exode 3:1)"},
        {id:31, t:"Qu'a demandé le roi Salomon à Dieu ?", o:["Richesse","Sagesse","Longue vie","Victoire"], c:1, l:2, r:"\"Accorde donc à ton serviteur un cœur intelligent pour juger ton peuple.\" (1 Rois 3:9)"},
        {id:32, t:"Qui est monté sur un sycomore pour voir Jésus ?", o:["Nicodème","Zachée","Bartimée","Lazare"], c:1, l:2, r:"\"Il courut en avant, et monta sur un sycomore pour le voir.\" (Luc 19:4)"},
        {id:33, t:"Qui fut le premier martyr chrétien (l'archidiacre) ?", o:["Jacques","Pierre","Étienne","Paul"], c:2, l:2, r:"\"Et ils lapidaient Étienne, qui priait et disait...\" (Actes 7:59)"},
        {id:34, t:"Qu'est-il arrivé au bâton d'Aaron dans la Tente du Témoignage ?", o:["Devenu serpent","A bourgeonné et fleuri","S'est brisé","A avalé les autres bâtons"], c:1, l:2, r:"\"La verge d'Aaron... avait fleuri, elle avait poussé des boutons, produit des fleurs.\" (Nombres 17:8)"},
        {id:35, t:"Quel était le nom de la belle-mère de Ruth la Moabite ?", o:["Orpa","Naomi","Sara","Marie"], c:1, l:2, r:"\"Ainsi revinrent Naomi et sa belle-fille Ruth.\" (Ruth 1:22)"},
        {id:36, t:"Combien de pierres David a-t-il prises pour affronter Goliath ?", o:["1","3","5","7"], c:2, l:2, r:"\"Il choisit dans le torrent cinq pierres polies.\" (1 Samuel 17:40)"},
        {id:37, t:"Quel prophète est monté au ciel dans un char de feu ?", o:["Élisée","Élie","Hénoc","Moïse"], c:1, l:2, r:"\"Voici, un char de feu... et Élie monta au ciel.\" (2 Rois 2:11)"},
        {id:38, t:"Quelle ville a vu ses murailles tomber après des cris et le son des trompettes ?", o:["Aï","Jéricho","Sichem","Gabaon"], c:1, l:2, r:"\"Le peuple poussa des cris... et la muraille s'écroula.\" (Josué 6:20)"},
        {id:39, t:"Quel disciple a douté de la résurrection du Christ ?", o:["Pierre","Thomas","Jean","Jacques"], c:1, l:2, r:"\"Si je ne vois... je ne croirai point.\" (Jean 20:25)"},
        {id:40, t:"Qui Jésus a-t-il ressuscité après quatre jours ?", o:["Simon","Lazare","Joseph","Judas"], c:1, l:2, r:"\"Lazare, sors !\" (Jean 11:43)"},
        {id:41, t:"Que signifie le nom 'Emmanuel' ?", o:["Dieu est amour","Dieu avec nous","Dieu voit","Dieu est fort"], c:1, l:2, r:"\"Emmanuel, ce qui signifie Dieu avec nous.\" (Matthieu 1:23)"},
        {id:42, t:"Qui sont les deux hommes qui soutenaient les mains de Moïse pendant la bataille ?", o:["Josué et Caleb","Aaron et Hur","Nadab et Abihu","Éléazar et Ithamar"], c:1, l:2, r:"\"Aaron et Hur soutenaient ses mains.\" (Exode 17:12)"},
        {id:43, t:"Dans quelle ville les disciples furent-ils appelés 'Chrétiens' pour la première fois ?", o:["Jérusalem","Rome","Antioche","Éphèse"], c:2, l:2, r:"\"Ce fut à Antioche que, pour la première fois, les disciples furent appelés chrétiens.\" (Actes 11:26)"},
        {id:44, t:"Combien de personnes Jésus a-t-il nourries avec 5 pains et 2 poissons ?", o:["3000","4000","5000","7000"], c:2, l:2, r:"\"Ceux qui avaient mangé étaient environ cinq mille hommes.\" (Matthieu 14:21)"},
        {id:45, t:"Quel roi a déchiré ses vêtements en entendant le Livre de la Loi ?", o:["Josias","Achaz","Manassé","Roboam"], c:0, l:2, r:"\"Lorsque le roi entendit les paroles du livre de la loi, il déchira ses vêtements.\" (2 Rois 22:11)"},
        {id:46, t:"Quel est le nom de l'île où Jean a écrit l'Apocalypse ?", o:["Chypre","Crète","Patmos","Malte"], c:2, l:2, r:"\"J'étais dans l'île appelée Patmos.\" (Apocalypse 1:9)"},
        {id:47, t:"Quelle reine a visité Salomon pour éprouver sa sagesse ?", o:["Saba","Jézabel","Athalie","Esther"], c:0, l:2, r:"\"La reine de Saba apprit la renommée de Salomon...\" (1 Rois 10:1)"},
        {id:48, t:"Quel prophète a reçu l'ordre d'épouser une femme prostituée comme symbole ?", o:["Osée","Amos","Joël","Habacuc"], c:0, l:2, r:"\"Va, prends-toi une femme prostituée.\" (Osée 1:2)"},
        {id:49, t:"Quel jour le Saint-Esprit est-il descendu sur les disciples ?", o:["Pâque","Tabernacles","Pentecôte","Ascension"], c:2, l:2, r:"\"Le jour de la Pentecôte... Et ils furent tous remplis du Saint-Esprit.\" (Actes 2:1-4)"},
        {id:50, t:"Quel est le chapitre le plus court de la Bible ?", o:["Psaume 117","Psaume 23","Psaume 150","Jean 2"], c:0, l:2, r:"(Le Psaume 117 ne contient que deux versets)."},
        {id:51, t:"Quel juge a fait le vœu d'offrir 'ce qui sortira de sa maison' en holocauste ?", o:["Gédéon","Jephté le Galaadite","Barak","Samson"], c:1, l:3, r:"\"Alors je l'offrirai en holocauste.\" (Juges 11:31)"},
        {id:52, t:"Quel était le nom de la mère de Jean-Baptiste ?", o:["Anne","Marie","Élisabeth","Salomé"], c:2, l:3, r:"\"Le temps où Élisabeth devait accoucher arriva.\" (Luc 1:57)"},
        {id:53, t:"Combien d'années les enfants d'Israël ont-ils habité en Égypte (selon l'Exode) ?", o:["400","430","450","480"], c:1, l:3, r:"\"Le séjour des enfants d'Israël en Égypte fut de quatre cent trente ans.\" (Exode 12:40)"},
        {id:54, t:"Qui est le jeune homme tombé du troisième étage et que Paul a relevé ?", o:["Timothée","Eutychus","Épaphrodite","Aristarque"], c:1, l:3, r:"\"Or, un jeune homme nommé Eutychus... tomba du troisième étage.\" (Actes 20:9)"},
        {id:55, t:"Quel est le nom du lieu où Jacob a lutté avec l'Ange ?", o:["Béthel","Peniel","Succoth","Mahanaïm"], c:1, l:3, r:"\"Jacob appela ce lieu du nom de Peniel.\" (Genèse 32:30)"},
        {id:56, t:"Quel roi a été chassé et a mangé de l'herbe comme les bœufs ?", o:["Belschatsar","Nabuchodonosor","Darius","Cyrus"], c:1, l:3, r:"\"Il mangea de l'herbe comme les bœufs.\" (Daniel 4:33)"},
        {id:57, t:"Quel prophète a annoncé la naissance du Christ à 'Bethléhem Éphrata' ?", o:["Ésaïe","Michée","Zacharie","Malachie"], c:1, l:3, r:"\"Et toi, Bethléhem Éphrata...\" (Michée 5:2)"},
        {id:58, t:"Quel était le nom de la femme de Moïse ?", o:["Séphora","Agar","Kétura","Miriam"], c:0, l:3, r:"\"Il donna sa fille Séphora à Moïse.\" (Exode 2:21)"},
        {id:59, t:"Quel disciple Paul appelait-il 'mon enfant légitime en la foi' ?", o:["Tite","Timothée","Philémon","Luc"], c:1, l:3, r:"\"À Timothée, mon enfant légitime en la foi.\" (1 Timothée 1:2)"},
        {id:60, t:"Combien de proverbes Salomon a-t-il prononcés (selon 1 Rois) ?", o:["1000","3000","1005","5000"], c:1, l:3, r:"\"Il a prononcé trois mille sentences (proverbes).\" (1 Rois 4:32)"},
        {id:61, t:"Qui est la personne que 'Dieu prit' et qui ne vit pas la mort dans la Genèse ?", o:["Hénoc","Mathusalem","Lémec","Seth"], c:0, l:3, r:"\"Hénoc marcha avec Dieu; puis... Dieu le prit.\" (Genèse 5:24)"},
        {id:62, t:"Quel est le nom du maître qui a enseigné la Loi à Paul ?", o:["Gamaliel","Caïphe","Anne","Nicodème"], c:0, l:3, r:"\"Instruit aux pieds de Gamaliel.\" (Actes 22:3)"},
        {id:63, t:"Quel âge avait Abraham à la naissance de son fils Isaac ?", o:["90","99","100","120"], c:2, l:3, r:"\"Abraham était âgé de cent ans.\" (Genèse 21:5)"},
        {id:64, t:"Quelle femme a tué 'Sisera' le chef de l'armée avec un pieu ?", o:["Jaël","Rahab","Dalila","Mical"], c:0, l:3, r:"\"Jaël... saisit un pieu de la tente.\" (Juges 4:21)"},
        {id:65, t:"Quel nom les enfants d'Israël ont-ils donné au serpent d'airain ?", o:["Léviathan","Nehuschtan","Béhémoth","Azazel"], c:1, l:3, r:"\"Et on l'appelait Nehuschtan.\" (2 Rois 18:4)"},
        {id:66, t:"Qui était le fils boiteux de Jonathan à qui David fit miséricorde ?", o:["Mephiboscheth","Isch-Boscheth","Absalom","Adonija"], c:0, l:3, r:"\"Mephiboscheth, fils de Jonathan... vint vers David.\" (2 Samuel 9:6)"},
        {id:67, t:"Jusqu'à quelle année la construction du temple a-t-elle cessé dans Esdras ?", o:["2e année de Darius","20e d'Artaxerxès","70e de captivité","7e de Cyrus"], c:0, l:3, r:"\"Jusqu'à la seconde année du règne de Darius.\" (Esdras 4:24)"},
        {id:68, t:"Quel prophète a prophétisé sur la 'Vallée des ossements desséchés' ?", o:["Ésaïe","Ézéchiel","Jérémie","Daniel"], c:1, l:3, r:"\"Il me déposa au milieu de la vallée; elle était remplie d'ossements.\" (Ézéchiel 37:1)"},
        {id:69, t:"Quel est le nom de l'ange qui a annoncé la bonne nouvelle à Zacharie ?", o:["Michel","Raphaël","Gabriel","Uriel"], c:2, l:3, r:"\"Je suis Gabriel, je me tiens devant Dieu.\" (Luc 1:19)"},
        {id:70, t:"Où Saül se cachait-il lorsqu'il a été choisi comme roi ?", o:["À la guerre","Au labour","Dans les bagages","Dans une grotte"], c:2, l:3, r:"\"Il s'est caché dans les bagages.\" (1 Samuel 10:22)"},
        {id:71, t:"Qui était le juge gaucher qui a tué Églon, roi de Moab ?", o:["Éhud","Othniel","Schamgar","Jephté"], c:0, l:3, r:"\"Éhud, fils de Guéra... qui était gaucher.\" (Juges 3:15)"},
        {id:72, t:"Depuis combien d'années le paralytique était-il malade à la piscine de Béthesda ?", o:["12","18","38","40"], c:2, l:3, r:"\"Là se trouvait un homme malade depuis trente-huit ans.\" (Jean 5:5)"},
        {id:73, t:"Vers quelle ville Jonas s'est-il enfui ?", o:["Tyr","Sidon","Tarsis","Jaffa"], c:2, l:3, r:"\"Pour s'enfuir à Tarsis.\" (Jonas 1:3)"},
        {id:74, t:"Qui était le prêtre qui a élevé le prophète Samuel ?", o:["Éli","Phinées","Hophni","Tsadok"], c:0, l:3, r:"\"Ils menèrent l'enfant à Éli.\" (1 Samuel 1:25)"},
        {id:75, t:"Quel était le nom de la première femme de David (fille de Saül) ?", o:["Abigaïl","Mical","Bath-Schéba","Achinoam"], c:1, l:3, r:"\"Et Saül lui donna pour femme Mical, sa fille.\" (1 Samuel 18:27)"},
        {id:76, t:"Qu'a utilisé Schamgar, fils d'Anath, pour tuer 600 hommes ?", o:["Une épée","Un aiguillon à bœufs","Une mâchoire d'âne","Une pierre de fronde"], c:1, l:4, r:"\"Il battit six cents hommes... avec un aiguillon à bœufs.\" (Juges 3:31)"},
        {id:77, t:"Quel est l'autre nom de 'Thaddée', l'un des douze ?", o:["Lebbée","Nathanaël","Simon","Matthias"], c:0, l:4, r:"\"Lebbée, surnommé Thaddée.\" (Matthieu 10:3)"},
        {id:78, t:"Qui a été décrit comme un 'vaillant chasseur devant l'Éternel' ?", o:["Ésaü","Nimrod","Ismaël","Samson"], c:1, l:4, r:"\"C'était un vaillant chasseur devant l'Éternel.\" (Genèse 10:9)"},
        {id:79, t:"Quel âge avait le roi Josias lorsqu'il est devenu roi ?", o:["8 ans","10 ans","12 ans","20 ans"], c:0, l:4, r:"\"Josias avait huit ans lorsqu'il devint roi.\" (2 Rois 22:1)"},
        {id:80, t:"Quel prophète était l'échanson du roi Artaxerxès ?", o:["Néhémie","Esdras","Daniel","Mardochée"], c:0, l:4, r:"\"J'étais alors échanson du roi.\" (Néhémie 1:11)"},
        {id:81, t:"Où trouve-t-on le verset 'Je fais mourir et je fais vivre, je blesse et je guéris' ?", o:["Job","Psaumes","Deutéronome 32","Ésaïe"], c:2, l:4, r:"\"Je blesse et je guéris.\" (Deutéronome 32:39)"},
        {id:82, t:"Qui était l'artisan rempli de l'Esprit pour construire le Tabernacle ?", o:["Betsaleel fils d'Uri","Oholiab","Hur","Phinées"], c:0, l:4, r:"\"Sache que j'ai choisi Betsaleel... Je l'ai rempli de l'Esprit de Dieu.\" (Exode 31:2-3)"},
        {id:83, t:"Combien de villes Salomon a-t-il données à Hiram qui ne lui plurent pas ?", o:["10","12","20","30"], c:2, l:4, r:"\"Vingt villes... Elles ne plurent point à ses yeux.\" (1 Rois 9:11-12)"},
        {id:84, t:"Pourquoi Démas a-t-il abandonné Paul ?", o:["Il avait peur","Il a aimé le siècle présent","Il était malade","Il a renié la foi"], c:1, l:4, r:"\"Car Démas m'a abandonné, par amour pour le siècle présent.\" (2 Timothée 4:10)"},
        {id:85, t:"Quel nom Moïse a-t-il donné à l'autel après la victoire sur Amalek ?", o:["Jéhovah Jireh","Jéhovah Nissi","Jéhovah Shalom","El Béthel"], c:1, l:4, r:"\"Et il lui donna pour nom: l'Éternel ma bannière (Jéhovah Nissi).\" (Exode 17:15)"},
        {id:86, t:"Quel roi a dit à Paul : 'Tu vas bientôt me persuader de devenir chrétien' ?", o:["Festus","Agrippa","Félix","Hérode"], c:1, l:4, r:"\"Et Agrippa dit à Paul: Tu vas bientôt me persuader de devenir chrétien !\" (Actes 26:28)"},
        {id:87, t:"Quelle était la longueur de l'arche de Noé (en coudées) ?", o:["100","300","500","700"], c:1, l:4, r:"\"La longueur de l'arche sera de trois cents coudées.\" (Genèse 6:15)"},
        {id:88, t:"Qui est mort parce qu'il a touché l'Arche de l'Alliance ?", o:["Uzza","Achjo","Obed","Nadab"], c:0, l:4, r:"\"Uzza étendit la main... et il mourut là.\" (2 Samuel 6:7)"},
        {id:89, t:"Quel orfèvre a provoqué une émeute à Éphèse contre Paul ?", o:["Alexandre","Démétrius","Gaïus","Aristarque"], c:1, l:4, r:"\"Un nommé Démétrius, orfèvre...\" (Actes 19:24)"},
        {id:90, t:"Quel roi avait un lit de fer de 9 coudées de long ?", o:["Og, roi de Basan","Sihon","Balak","Kedorlaomer"], c:0, l:4, r:"\"Og, roi de Basan... Son lit, un lit de fer... a neuf coudées de longueur.\" (Deutéronome 3:11)"},
        {id:91, t:"Sur quelle montagne le prêtre Aaron est-il mort ?", o:["Nébo","Hor","Sinaï","Oliviers"], c:1, l:4, r:"\"Aaron mourut là, au sommet de la montagne (Hor).\" (Nombres 20:28)"},
        {id:92, t:"Quelle était la couleur du troisième cheval dans l'Apocalypse ?", o:["Blanc","Rouge","Noir","Vert"], c:2, l:4, r:"\"Et voici, parut un cheval noir. Celui qui le montait tenait une balance.\" (Apocalypse 6:5)"},
        {id:93, t:"Quel prophète a parlé du Christ en disant 'Blessé dans la maison de mes amis' ?", o:["Ésaïe","Jérémie","Zacharie","Malachie"], c:2, l:4, r:"\"C'est que j'ai été blessé dans la maison de ceux qui m'aimaient.\" (Zacharie 13:6)"},
        {id:94, t:"Qui était responsable des chameaux de David ?", o:["Obil l'Ismaélite","Jaziz","Schimeï","Baal"], c:0, l:4, r:"\"Sur les chameaux: Obil, l'Ismaélite.\" (1 Chroniques 27:30)"},
        {id:95, t:"Quel est le nom hébreu du lieu où Pilate s'assit pour le jugement (Le Pavé) ?", o:["Golgotha","Gabbatha","Akeldama","Gethsémané"], c:1, l:4, r:"\"Au lieu appelé le Pavé, et en hébreu Gabbatha.\" (Jean 19:13)"},
        {id:96, t:"Quel prophète a reçu l'ordre de cuire son pain sur des excréments de bœuf ?", o:["Ézéchiel","Jérémie","Daniel","Osée"], c:0, l:4, r:"\"Je te donne de la fiente de bœuf au lieu d'excréments humains.\" (Ézéchiel 4:15)"},
        {id:97, t:"Combien de villes de refuge Josué a-t-il désignées ?", o:["3","6","10","12"], c:1, l:4, r:"\"Ils consacrèrent Kédesch... Sichem... Kirjath-Arba...\" (Josué 20 - Total 6)."},
        {id:98, t:"Qui est le vaillant homme qui a tué 800 hommes en une seule fois ?", o:["Joscheb-Basschébeth (Adino)","Éléazar","Schamma","Abischaï"], c:0, l:4, r:"\"Il brandit sa lance sur huit cents hommes, qu'il fit périr en une seule fois.\" (2 Samuel 23:8)"},
        {id:99, t:"Quel roi n'a régné sur Israël que 7 jours ?", o:["Zimri","Omri","Tibni","Nadab"], c:0, l:4, r:"\"Zimri régna sept jours à Thirtsa.\" (1 Rois 16:15)"},
        {id:100, t:"Quel est le nom de la mère de David ?", o:["Non mentionné dans la Bible","Nitzevet","Hazlelponi","Marie"], c:0, l:4, r:"(Il n'y a pas de texte explicite nommant la mère de David dans la Bible)."}
    ],

    
};
